language: csharp
solution: RomainConvert.sln
mono: none 
dotnet: 2.0.0 
dist: trusty 
script: 
- dotnet restore
- dotnet test ./TestRomainConvert/TestRomainConvert.csproj 
- dotnet build -c Release 
- dotnet publish -c Release -o ./RomainConvert/publish